version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: personal_website_db
    environment:
      POSTGRES_DB: personal_website
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: